In [4]:
import numpy as np

In [8]:
a = np.ones(3)

In [9]:
a

array([1., 1., 1.])

In [12]:
my_list = [2, 3, 4]
array_from_list = np.array(my_list)

In [13]:
array_from_list

array([2, 3, 4])

In [26]:
for n in my_list:
    print(n)

2
3
4


In [27]:
c = {1,2,3}

In [29]:
for n in c:
    print(n)

1
2
3


In [30]:
my_set = {4, 2, 3, 2, 4}
print(my_set) # Output: {1, 2, 3, 4} (order may vary)
my_set.add(5)
print(my_set) # Output: {1, 2, 3, 4, 5} (order may vary)

{2, 3, 4}
{2, 3, 4, 5}


In [31]:
my_dict= {"1":"Sundar", "2":"kumar"}

In [33]:
print(my_dict["1"])

Sundar


In [39]:
for value in my_dict.values():
    print(value)

Sundar
kumar


In [43]:
u=np.array([1,2,3,4])
v=np.array([5,6,7,8])

In [44]:
u.dot(v)

70

In [7]:
def vector_vector_multiplication(u,v):
    assert(u.shape[0]==v.shape[0])
    n = u.shape[0]
    result=0
    for i in range(n):
       result = result + u[i] * v[i]
    
    return result
    

In [51]:
vector_vector_multiplication(u,v)

70

In [59]:
u=np.array([
          [1,2,3,1],
          [4,5,6,2],
          [7,8,9,3],
        ])

In [8]:
def matrix_vector_multiplication(u,v):
    assert(u.shape[1]==v.shape[0])
    num_rows = u.shape[0]
    result = np.zeros(num_rows)
    for i in range(num_rows):
       result[i] = vector_vector_multiplication(u[i],v)
    
    return result
    

In [64]:
v.shape[0]

4

In [65]:
matrix_vector_multiplication(u,v)

array([ 46., 108., 170.])

In [66]:
u.dot(v)

array([ 46, 108, 170])

In [67]:
v=np.array([
          [1,2,3],
          [4,5,6],
          [7,8,9],
          [10,11,12],
        ])

In [85]:
u

array([[1, 2, 3, 1],
       [4, 5, 6, 2],
       [7, 8, 9, 3]])

In [26]:
def matrix_matrix_multiplication(u,v):
    assert(u.shape[1]==v.shape[0])
    num_rows = u.shape[0]
    num_cols = u.shape[1]
    print (num_rows, num_rows)
    print(u,v)
    result = np.zeros((num_rows, num_rows))
    for i in range(num_rows):
        vec = v[:,i]
        print(vec)
        result[:,i] = matrix_vector_multiplication(u,vec)
    print (result)
    return result
    

In [2]:
v

NameError: name 'v' is not defined

In [9]:
u=np.array([
          [1,2,3,1],
          [4,5,6,2],
          [7,8,9,3],
        ])

In [10]:
v=np.array([
          [1,2,3],
          [4,5,6],
          [7,8,9],
          [10,11,12],
        ])

In [27]:
matrix_matrix_multiplication(u,v)

3 3
[[1 2 3 1]
 [4 5 6 2]
 [7 8 9 3]] [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  4  7 10]
[ 2  5  8 11]
[ 3  6  9 12]
[[ 40.  47.  54.]
 [ 86. 103. 120.]
 [132. 159. 186.]]


array([[ 40.,  47.,  54.],
       [ 86., 103., 120.],
       [132., 159., 186.]])

In [17]:
u.dot(v)

array([[ 40,  47,  54],
       [ 86, 103, 120],
       [132, 159, 186]])